# Application
spring.application.name=cafeteria-system

# H2 Database
spring.datasource.url=jdbc:h2:file:./cafeteria-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080